services:
  unitn-ap-api-dev:
    build:
      context: ..
      dockerfile: infra/docker/dev.Dockerfile
    container_name: unitn-ap-api-dev
    working_dir: /workspace
    env_file:
      - .dev.env
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        exec sleep infinity
      "